### ISSUE TITLE
Failed to activate the themed-settings package

### ISSUE THREAD

**Issue by jasonmccallister** [postcasio/themed-settings#5]
[Enter steps to reproduce below:]

1.Enabled the theme.

**Atom Version**: 0.192.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [themed-settings](https://github.com/postcasio/themed-settings) package, v1.0.1
### Stack Trace

Failed to activate the themed-settings package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.activate (/Users/jasonmccallister/.atom/packages/themed-settings/lib/themed-settings.coffee:10:18)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:222:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:203:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:147:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:434:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:303:19
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:559:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:721:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:536:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:220:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:330:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:132:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:132:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:213:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```
### Commands

```
  2x -1:08.0 core:close (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-terminal",
      "linter",
      "metrics",
      "background-tips",
      "atom-lint",
      "autocomplete",
      "dev-live-reload",
      "open-on-github",
      "project-ring",
      "term",
      "terminal-status",
      "html2haml",
      "language-haml",
      "welcome",
      "language-mustache",
      "language-toml",
      "link",
      "ruby-bundler",
      "space-tab",
      "vim-mode",
      "autocomplete-plus",
      "craft-snippets",
      "foundation5-snippets",
      "atom-bourbon-snippets",
      "gulp-helper",
      "emmet",
      "color-gutter",
      "language-twig",
      "php-twig",
      "sassbeautify",
      "gulp-control",
      "project-quick-open",
      "autocomplete-snippets",
      "laravel",
      "linter-php"
    ],
    "themes": [
      "predawn-ui",
      "predawn-syntax"
    ],
    "projectHome": "~/Websites"
  }
}
```
### Installed Packages

``` coffee
# User
docblockr, v0.6.3
file-icons, v1.5.4
git-plus, v4.4.13
language-blade, v0.12.0
predawn-syntax, v0.1.3
predawn-ui, v0.3.8
project-manager, v1.15.5
themed-settings, v1.0.1

# Dev
No dev packages
```

**Comment by sweptr** [comment]
bug confirmed today at Ubuntu Xenial 64

**Comment by marnen** [comment]
Still happening in 1.15.0 on Mac OS X 10.12.

**Comment by ghost** [comment]
Confirmed for Atom 1.16.0 x64 , addon version 1.0.1, Ubuntu 17.04

**Comment by C0D3R4** [comment]
Any update how fix it ? Cheers.
